# 记录日志和检查点的目录
log_dir: snapshot

dataset:
  dataloader_settings: # 数据加载设置
    train: # 训练数据加载器的设置
      batch_size: 4 # 每个批次的样本数量
      drop_remainder: True # 是否丢弃最后一个批次的不完整样本
      shuffle: True # 是否在每个 epoch 开始前打乱数据
      num_parallel_calls: 6 # 数据加载的并行调用数
    val: # 验证数据加载器的设置
      batch_size: 1 # 每个批次的样本数量
  data_dir: dataset/REDS/ # 数据集的目录
  degradation: sharp_bicubic # 图像退化类型
  train_frame_num: 10 # 每次训练步骤中使用的图像帧数量
  test_frame_num: 100 # 每次测试步骤中使用的图像帧数量
  crop_size: 64 # 裁剪图像的高度和宽度

model:
  path: model/mobile_rrn.py # 模型文件的路径
  name: MobileRRN # 模型类的名称

learner:
  general:
    total_steps: 15000 # 总训练步骤数 默认1500000
    log_train_info_steps: 100 # 记录训练信息的频率（每隔多少步骤）
    keep_ckpt_steps: 10000 # 保存检查点的频率（每隔多少步骤）
    valid_steps: 100000 # 验证频率（每隔多少步骤）

  optimizer: # 优化器设置
    name: Adam # 使用的优化器名称
    beta_1: 0.9 # Adam 优化器的第一个动量参数
    beta_2: 0.999 # Adam 优化器的第二个动量参数

  lr_scheduler: # 学习率调度器设置
    name: ExponentialDecay # 学习率调度器名称
    initial_learning_rate: 0.0001 # 初始学习率
    decay_steps: 1000000 # 学习率衰减的步数
    decay_rate: 0.1 # 学习率衰减率
    staircase: True # 是否使用阶梯衰减

  saver:
    restore_ckpt: snapshot/ckpt-2 # 从哪个检查点恢复（如果为 null，则不恢复）
    # 在 TensorFlow 中，ckpt-2 是检查点的前缀，实际的文件包括 .index 和 .data-00000-of-00001 等文件扩展名，但在使用 Checkpoint.restore() 时，通常只需要指定检查点文件的前缀，而不是具体的文件名或扩展名。
