dataset:
  crop_size: 64
  data_dir: /data/mai22/dataset/orignal/REDS
  dataloader_settings:
    train:
      batch_size: 4
      drop_remainder: true
      num_parallel_calls: 6
      shuffle: true
    val:
      batch_size: 1
  degradation: sharp_bicubic
  test_frame_num: 100
  train_frame_num: 10
learner:
  general:
    keep_ckpt_steps: 200
    log_train_info_steps: 100
    total_steps: 10000
    valid_steps: 200
  lr_scheduler:
    decay_rate: 0.1
    decay_steps: 1000000
    initial_learning_rate: 0.0001
    name: ExponentialDecay
    staircase: true
  optimizer:
    beta_1: 0.9
    beta_2: 0.999
    name: Adam
  saver:
    restore_ckpt: snapshot/ckpt-51
log_dir: snapshot
model:
  name: MobileRRN
  path: model/mobile_rrn.py
